language: node_js
node_js:
  - "14.13.1"
branches:
  only:
    - master
before_deploy: # 배포하기전 하는 작업들
  - npm install -g browserify
  - browserify src/index.js -o output/js/main.js # output/js 폴더에 번들링
  - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
  - cp index.html output 
script:
  - echo "skipping tests" # 테스트 스킵
deploy:
  provider: pages
  local_dir: output # 배포 폴더
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - vvsos1@hotmail.co.kr