language: node_js
node_js:
  - "14.13.1"
branches:
  only:
    - master
before_deploy: # 배포하기전 하는 작업들
  - npm install -g browserify # browserify 설치
  - browserify src/js/tree/index.js -do output/js/tree/index.js # tree 페이지에 들어갈 js를 번들링
  - browserify src/js/sort/index.js -do output/js/sort/index.js  # sort 페이지에 들어갈 js 번들링
  - browserify src/js/hashtable/index.js -do output/js/hashtable/index.js # hash 페이지에 들어갈 js 번들링
  - browserify src/js/stack/index.js -do output/js/stack/index.js # stack 페이지에 들어갈 js 번들링
  - mkdir output/js/static
  - cp src/js/static/* output/js/static # static js파일 (jquery, bootstrap) 복사
  - cp src/view/* output # view 파일들 복사
  - mkdir output/css
  - cp src/css/* output/css # css 파일들 복사
  - mkdir output/img
  - cp src/img/* -r output/img # img 파일들 복사
  - mkdir output/font
  - cp src/font/* output/font # font 파일들 복사
  - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
script:
  - echo "skipping tests" # 테스트 스킵
deploy:
  provider: pages
  local_dir: output # 배포 폴더
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - vvsos1@hotmail.co.kr
