language: node_js
node_js:
  - "14.13.1"
branches:
  only:
    - master
before_deploy: # 배포하기전 하는 작업들
  - build.sh
script:
  - echo "skipping tests" # 테스트 스킵
deploy:
  provider: pages
  local_dir: output # 배포 폴더
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - vvsos1@hotmail.co.kr