language: node_js
node_js:
  - "14.13.1"
branches:
  only:
    - master
before_deploy: # 배포하기전 하는 작업들
  - npm install -g browserify # browserify 설치
  - browserify src/avl-tree/index.js -o output/js/avl-tree/index.js # avl tree 페이지에 들어갈 js를 번들링
  - cp src/view/avlTree.html output/avlTree.html    # avl tree html 파일을 복사 
  - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
script:
  - echo "skipping tests" # 테스트 스킵
deploy:
  provider: pages
  local_dir: output # 배포 폴더
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - vvsos1@hotmail.co.kr